project:
  type: website
  output-dir: docs/
  execute-dir: project 
  render:
    - "*.qmd"
    - "!original_code/"
    - "!new_code/"
  resources:
    - "new_code/competence_effort/Experiment/img/example1.png"
    - "new_code/competence_effort/Experiment/img/table.png"