[workspace]
authors = ["jczimm <jczimm@jczimm.com>"]
channels = ["conda-forge"]
name = "xiang2023"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
install_non_conda = "Rscript -e \"remotes::install_github('crsh/papaja@v0.1.4')\""
preview = "quarto preview"
render = "quarto render"

[dependencies]
r-base = ">=4.5.1,<4.6"
quarto = ">=1.8.25,<2"
r-knitr = ">=1.50,<2"
r-rmarkdown = ">=2.30,<3"
r-tidyverse = ">=2.0.0,<3"
r-lmertest = ">=3.1_3,<4"
r-effectsize = ">=1.0.1,<2"
r-pwr = ">=1.3_0,<2"
r-hmisc = ">=5.2_4,<6"
r-osfr = ">=0.2.9,<0.3"
r-httpgd = ">=2.0.4,<3"
r-openssl = ">=2.3.4,<3"
r-remotes = ">=2.5.0,<3"
r-ggh4x = ">=0.3.1,<0.4"
